src/redux/initialState.js
Very trivial fix, so forewent any discussion.  Let me know if I should do this differently in the future, first time contributing on GitHub.
=> Fixed tooltips for the Top Panel zoom buttons.  They were reversed.

src/components/CustomElement/CustomElement.js, src/components/DocumentContainer/DocumentContainer.js, src/components/LeftPanel/LeftPanel.js, src/components/LeftPanelTabs/LeftPanelTabs.js, src/components/LoadingModal/LoadingModal.js, src/components/OutlinesPanel/OutlinesPanel.js, src/helpers/isDataElementPanel.js, src/redux/actions/exposedActions.js, src/redux/initialState.js, src/redux/reducers/viewerReducer.js, src/redux/selectors/exposedSelectors.js
Tested with:
```javascript
readerControl.setCustomPanel({
tab:{
dataElement: 'customPanelTab',
title: 'customPanelTab',
img: 'https://pbs.twimg.com/profile_images/927446347879292930/Fi0D7FGJ_400x400.jpg',
},
panel: {
dataElement: 'customPanel',
render: () => {
const div = document.createElement('div');
div.innerHTML = 'Hello World';
return div;
}
}
});
```
Also tested:
```javascript
readerControl.setActiveLeftPanel('customPanel');
readerControl.openElement('customPanel');
readerControl.closeElement('customPanel');
```
=> [new] resolves #29

src/components/CustomElement/CustomElement.js, src/components/LeftPanel/LeftPanel.js, src/components/LeftPanel/LeftPanel.scss, src/components/NotesPanel/NotesPanel.scss, src/components/OutlinesPanel/OutlinesPanel.scss, src/components/ThumbnailsPanel/ThumbnailsPanel.scss
Add class 'Panel' to custom panels, also make sure that custom panel have flex-grow 1
=> [update] resolves #29

src/helpers/downloadPdf.js
New filename option in getDownloadLink allows the new name to be changed
=> Allow changing of file download name when using WebViewer Server

i18n/translation-nl.json
This is a translation file for the Dutch language, so that dutch readers can use PDFTron in Dutch.
=> Add dutch translation

src/components/PageNavOverlay/PageNavOverlay.js
Fixed the issue caused when pageNavOverlay was disabled by adding a new conditional to the styling statement.
=> [bugfix] fixes #116

src/components/PrintModal/PrintModal.js
isPrinting should be true when the page count is 0 because we set it to -1 when not printing
If we wait until the count is 1 then if the first page takes a while to complete it looks like nothing happened after pressing print
=> Show feedback about processing pages immediately after pressing print button

src/helpers/getPopupPosition.js
Modified annotation popup positioning so the popup is centered when the bottom margin of the annotation is too narrow
=> [bugfix] Fixed annotation popup positioning issue

src/apis/disableRedaction.js, src/apis/enableRedaction.js, src/apis/index.js, src/components/RedactionOverlay/RedactionOverlay.js, src/index.js
Added API for enabling redaction.
=> [Update]Added "enable redaction" to API

src/components/RedactionOverlay/RedactionOverlay.js, src/core/index.js, src/core/isApplyRedactionEnabled.js, src/event-listeners/onDocumentLoaded.js, src/redux/initialState.js
I realized I was using "isFullPDFEnabled" instead of "isApplyRedactionEnabled " for when to show the "Apply" button for redactions.
=> [bugfix] Web server redaction fix

src/apis/downloadPdf.js, src/components/DocumentContainer/DocumentContainer.js
Also update the wheel event for document container to use passive: false otherwise Chrome 73 will error in the console. https://www.chromestatus.com/features/6662647093133312
=> [bugFix] Fixed issue where downloadPdf API doesn't allow downloading office files

i18n/translation-fr.json, i18n/translation-nl.json, i18n/translation-zh_cn.json, package.json, scripts/translationCheck.js
- Migrate translation check from legacy-ui to the new UI. Also tried to hook up with google translation to automatically translate missing keys but failed. If interested we can talk...
- I18ned several missing keys
=> [Update] Add missing i18n

src/components/ToolGroupButton/ToolGroupButton.js
=> [bugfix] Fix issue where calling setToolMode API with different tool names will blow up the app

src/components/Icon/Icon.scss, src/components/ToggleElementOverlay/ToggleElementOverlay.scss, src/components/ZoomOverlay/ZoomOverlay.js
* Test in input correctly addapts to color
* Triangle addapts to color
* Marquee zoom addapts to color
Before & After
=> Fixes dark theme issues for zoomOverlayButton & ZoomOverlay

i18n/translation-en.json, src/components/ProgressModal/ProgressModal.js, src/constants/supportedFiles.js, src/event-listeners/onDocumentLoaded.js, src/helpers/loadDocument.js, src/redux/actions/internalActions.js, src/redux/initialState.js, src/redux/reducers/documentReducer.js, src/redux/selectors/exposedSelectors.js
When PDFTron server is set, and a blob is passed to `loadDocument`, automatically upload it instead of erroring.
=> Auto upload blobs

src/components/Note/Note.js
Fixed bug where notes collapses when a reply is made.
=> [bugfix] Note collapse bug fixed

src/constants/map.js
Fixed polygon icon not appearing in the left notes panel
=> [bugfix] Fixed polygon icon not appearing in left panel

src/components/ProgressModal/ProgressModal.js, src/event-listeners/onDocumentLoaded.js, src/helpers/loadDocument.js, src/redux/actions/internalActions.js, src/redux/initialState.js, src/redux/reducers/documentReducer.js, src/redux/selectors/exposedSelectors.js
Adding the pull request from #234 to 5.1 .
=> [update] Merging changes from dev to 5.1.0

src/index.js
Update for checking if UI and Core versions are compatible
=> [Update] Version checking

src/components/DocumentContainer/DocumentContainer.js, src/index.js
=> [bugfix] Fixed issue where viewerLoaded event is triggered before setViewerElement is called

src/event-listeners/onDocumentLoaded.js
@mparizeau-pdftron did I do correct here?
=> [bugfix] error message saying forceClientSideInit required

package-lock.json, src/apis/index.js, src/apis/setMeasurementUnits.js, src/components/AnnotationStylePopup/AnnotationStylePopup.js, src/components/MeasurementOption/MeasurementOption.js, src/components/MeasurementOverlay/MeasurementOverlay.js, src/components/MeasurementsDropdown/MeasurementsDropdown.js, src/components/MeasurementsDropdownItem/MeasurementsDropdownItem.js, src/components/StylePopup/StylePopup.js, src/components/ToolStylePopup/ToolStylePopup.js, src/helpers/getAnnotationStyles.js, src/helpers/setToolStyles.js, src/index.js, src/redux/actions/exposedActions.js, src/redux/initialState.js, src/redux/reducers/viewerReducer.js, src/redux/selectors/exposedSelectors.js
- expose a `setMeasurementUnits` API to make the units in the measurement dropdown customizable
- show precision and scale options for measurement annotations so these properties can be adjusted after created
=> [upgrade] Measurement Tools

src/helpers/getPopupPosition.js
=> Fix positioning of annotation popup for rotated documents

src/helpers/loadDocument.js, src/redux/selectors/exposedSelectors.js
Changed overall loading progress when not uploading as the average of both worker and file loading progress.
=> Fixed seemingly idle progress bar

i18n/translation-en.json, src/components/NotePopup/NotePopup.js, src/components/NotePopup/NotePopup.scss, src/components/NoteRoot/NoteRoot.js, src/components/NoteRoot/NoteRoot.scss
Added new functionality for annotation state. User is able to add, change, delete annotation state.
=> [upgrade] annotation-state-ui

src/apis/index.js, src/apis/setMaxSignaturesCount.js, src/components/SignatureOverlay/SignatureOverlay.js, src/index.js, src/redux/actions/exposedActions.js, src/redux/initialState.js, src/redux/reducers/viewerReducer.js, src/redux/selectors/exposedSelectors.js
Added an API for signature count. I'm not too sure about the "onSaveDefault" function in the SignatureOverlay.js file
=> [Feature] Added API for setting max number of signatures

README.md
Include invisible image to connect with Google Analytics
=> Include Onepixel Tracker

src/helpers/setDefaultToolStyles.js
This fix is for a ticket. They are hosting their 'lib' folder in another domain and setting "path" to that domain. The problem is the js file isn't allowed to accessed localStoage if third-party cookies are disabled in the browsers (this throw an exceptions and crash the UI)
=> [bugfix] Add check for localStorage

src/components/Slider/Slider.js
Update slider width when window resizes
=> [bugfix] Update slider width when window width changes

src/components/ErrorModal/ErrorModal.js, src/helpers/loadDocument.js
=> [misc] Also fireError when the error is an object

src/helpers/downloadPdf.js
=> [update] change to getFileData

src/components/NotePopup/NotePopup.js, src/core/canModifyContents.js, src/core/index.js
We were missing support for "LockedContents".  The following is what it looked like in the legacy UI
=> [Bugfix]Added missing "LockContents" support

package-lock.json, package.json
Updates dependancy to use a fork with the bug fixed
=> [Bugfix] Fixed command mod key in FF mac

package-lock.json, package.json
PR got merged so we can revert this back!
=> Hot keys revert

src/helpers/device.js
Fix for being unable to tell that ios v13 is mobile
=> [Bugfix] fix for IOS13 check

src/components/PrintModal/PrintModal.js, src/helpers/device.js
added command that always seems to work with safari 11 and fallback for firefox
=> [Bugfix] Safari print hang

src/event-listeners/onPageComplete.js
Fix for page text showing up in front of canvas sometimes
=> Fix for page text showing up in front of canvas sometimes

src/event-listeners/onBeforeDocumentLoaded.js
https://app.xodo.com/latest/#/team/-KEc2Okvm9KcebWPhOb7/-KEc5qegeJvXsdOP5db-?msgId=-LsO2gFYExFjBvx2QnXL
=> Always apply 500 page limit

src/components/SearchOverlay/SearchOverlay.js, src/components/SearchOverlay/SearchOverlay.scss
- Updated single search behaviour to indicate to user if there are no results
=> [Upgrade] Updated single search behaviour

src/apis/disableReplyForAnnotations.js, src/apis/index.js, src/components/Note/Note.js, src/helpers/documentContainerHelper.js, src/redux/actions/internalActions.js, src/redux/initialState.js, src/redux/reducers/viewerReducer.js, src/redux/selectors/exposedSelectors.js
Need help in better variable naming.
=> [Feature] disable reply for annotations

src/components/SearchResult/SearchResult.scss
=> Bug fix/search results text overflow

src/event-listeners/onDocumentLoaded.js, src/helpers/logDebugInfo.js
Makes the log nicer, also adds the build number to the log
=> Change log to a table to display debug information

src/components/SearchOverlay/SearchOverlay.js
- Fixed an issue where the search stopped on first page
- Fixed an issue where on search restart would show 'No results found'
=> [Bugfix] Single search stops on page one

src/event-listeners/onPageComplete.js
bug fix for https://trello.com/c/3aQH02v2/635-in-accessiblemode-sometimes-the-page-gets-pushed-down-by-the-text-element
=> Bug fix/accessible mode page push down

src/components/PrintHandler/PrintHandler.js, src/components/PrintHandler/PrintHandler.scss
Only apply Safari workaround on iOS devices as the CSS causes
the printing problem for IE and Edge.
=> Fix issue with only printing the first page in IE and Edge

src/components/Thumbnail/Thumbnail.js, src/components/Thumbnail/Thumbnail.scss, src/redux/actions/internalActions.js, src/redux/initialState.js
Some bug I found after more testing.  For the adding the "thumbnail" div back, I thought it was working before, but it could have just been my browser caching something. It seems I can't use pseudo element with canvas so I added the div back
https://stackoverflow.com/questions/15593043/impossible-to-add-pseudo-element-to-canvases
=> [Bugfix] Some bug fixes for thumbnails

src/configorigin.txt, src/helpers/loadScript.js, webpack.config.prod.js
Only allow the same origin to send a message or specifically allowed origins
=> Add extra checks for loading config files

src/components/StyleOption/StyleOption.js, src/components/StyleOption/StyleOption.scss, src/components/StyleOption/index.js, src/components/StylePopup/StylePopup.js
- Add new tool style popup to change the rectangle tool between regular and cloudy style. Make sure you have [this branch ](https://github.com/XodoDocs/webviewer/pull/709)checked out and that you follow the instructions on there.
=> [FEATURE] Add new style option tool for rectangles to choose style

src/components/LinkModal/LinkModal.js
- Instead of only allowing linking one annotation at a time, allow multiple annotations to be linked.
=> [Feature] Allow multiple annotations to be linked

.gitignore
ignore package-lock. Too annoying to deal with this file. Always has changes across mac and windows.
=> [CHANGE] ignore package-lock

src/helpers/loadDocument.js, src/index.js, src/redux/initialState.js
Need to pass these options to docViewer.loadDocument now
=> Fix issue where backendType option wasn't being passed along to document loading

src/components/Thumbnail/Thumbnail.js
=> [Bugfix] Thumbnail loading web viewer server 5.0

src/components/AnnotationPopup/AnnotationPopup.js, src/components/LinkModal/LinkModal.scss
- Fixed the link button sizing for different languages
- Disable linking for comments since comments resize
=> [Bug] Link Button Sizing

i18n/translation-de.json, src/components/NotePopup/NotePopup.js
- Fixed display author vs author
- Fixed translations
=> [Bug] Fixed translations

src/components/NotePopup/NotePopup.js
- Get display author after state updated
Related to ticket https://support.pdftron.com/a/tickets/11884
=> [Bug] Get display author after state update on annotation

src/helpers/logDebugInfo.js, src/index.js, src/redux/initialState.js, src/redux/selectors/exposedSelectors.js
The state isn't actually used but I made it for future use. Relies on https://github.com/XodoDocs/webviewer/pull/864
=> Adds disableLogs state and stops the debug info logs if it is set

src/apis/index.js, src/apis/setNoteTransformFunction.js, src/components/Note/Note.js, src/redux/actions/internalActions.js, src/redux/initialState.js, src/redux/reducers/viewerReducer.js, src/redux/selectors/exposedSelectors.js
Download env: `npm run get-env -- --key note-transform-8D8mkf`
=> [CHANGE] Adds 'dangerouslySetNoteTransformFunction' which can be used to transform content inside notes

jsconfig.json
Enables click-through on all non-relative paths, may enable some auto-import behaviour as well.
See:
https://code.visualstudio.com/docs/languages/jsconfig
=> chore(vscode): added jsconfig.json file for allowing click-through

src/components/AnnotationPopup/AnnotationPopup.js, src/components/AnnotationPopup/AnnotationPopup.scss, src/components/ContextMenuPopup/ContextMenuPopup.js, src/components/TextPopup/TextPopup.js, src/constants/popup.scss, src/helpers/createPopupAPI.js
https://trello.com/c/J0avN9BX/776-popup-api-bugs
=> Bug fix/pop up api bugs

src/helpers/loadDocument.js, src/index.js
Calls the view state API if constructor option is set.
https://github.com/XodoDocs/webviewer/pull/885
=> [AEC] Annotation state

src/components/Dropdown/Dropdown.js, src/components/Dropdown/Dropdown.scss, src/components/NotesPanel/NotesPanel.scss, src/constants/sortStrategies.js
Before:
After:
Note that there is a hover effect on hover of the drop down menu items
=> Bug fix/note panel styling

src/components/NoteTextarea/MentionsTextarea/MentionTextArea.scss
@ZhijieZhang this fixes my background-color issue.
=> Update mention style.

src/components/MeasurementOverlay/LineMeasurementInput.js
LCT requested hen enter is pressed in edit mode for
length or angle, that the annotation is finished.
=> Add onkey for Enter

src/components/Thumbnail/Thumbnail.js, src/components/ThumbnailsPanel/ThumbnailsPanel.js, src/helpers/pageManipulation.js
This PR is for moving pages between instance of WebViewer
Forgot to set #535 to ready to review and had issue merging master into it
=> [Feature] Moving pages between instance of WebViewer 

src/components/Thumbnail/Thumbnail.js, src/components/ThumbnailsPanel/ThumbnailsPanel.js, src/helpers/setDefaultDisabledElements.js
Enable thumbnail controls by default
=> [Feature] Enable feature by default

src/components/FilePickerHandler/FilePickerHandler.js
Same as #594 but for 6.3 release
=> [Bugfix ]Change allowed file type for PDF Server

src/apis/extractPagesWithAnnotations.js, src/helpers/extractPagesWithAnnotations.js
Same as # 598
Fix some documentation and rename some variables
=> [Bugfix] Fix extractPagesWithAnnotations documentation for 6.3

src/apis/extractPagesWithAnnotations.js, src/helpers/extractPagesWithAnnotations.js
Fix some documentation and rename some variables
=> [Bugfix] Fix extractPagesWithAnnotations documentation

src/helpers/setDefaultDisabledElements.js, src/redux/initialState.js
Enable selecting pages and the "document controls" by default
=> [Update ] Enable Selecting thumbnails by default

i18n/translation-en.json
=> [Bugfix] Add missing translation

src/components/Button/Button.js, src/components/Tooltip/Tooltip.js
#	src/components/Button/Button.js
=> Bugfix/enable tooltip disabled button (#632)

src/helpers/hotkeysManager.js
Fixed hotkeys for opening up search.
=> fix(hotkeys): ctrl / command + f to open search

src/components/SearchOverlay/SearchOverlay.js
Search bar wasn't focusing when search panel opened.
=> fix(search): focus search when panel opened

src/apis/searchText.js, src/apis/searchTextFull.js, src/components/SearchOverlay/SearchOverlay.js, src/components/SearchPanel/SearchPanel.js
Open panel when using programmatic search.
=> fix(search): open panel for programmatic search

src/apis/index.js, src/apis/setAnnotationContentOverlayHandler.js, src/components/AnnotationContentOverlay/AnnotationContentOverlay.js, src/redux/actions/exposedActions.js, src/redux/initialState.js, src/redux/reducers/viewerReducer.js, src/redux/selectors/exposedSelectors.js
Alread reviewed here: https://github.com/PDFTron/webviewer-ui/pull/650
=> [CHANGE] Add API to customize annotation tooltips (#650)

src/components/Slider/Slider.js, src/components/StylePopup/StylePopup.js
=> [Legacy][Bugfix] Fixed sliders to use data-element

src/components/Slider/Slider.js, src/components/StylePopup/StylePopup.js
=> [Bugfix] Fixed sliders to use data-element

package.json, src/components/Choice/Choice.js, src/components/PrintModal/PrintModal.js, src/components/PrintModal/PrintModal.scss, src/components/PrintModal/WatermarkModal/WatermarkModal.js, src/components/PrintModal/WatermarkModal/WatermarkModal.scss, src/components/SearchOverlay/SearchOverlay.js
- Added `Choice` component from toolkit
- Added `FocusTrap` from toolkit to specific modals
=> A11y updates

src/components/AnnotationContentOverlay/AnnotationContentOverlay.js
Merged into master already https://github.com/PDFTron/webviewer-ui/pull/665
=> Tooltip perf (#665)

src/helpers/loadScript.js
This is relevant in the case that the origin is null
=> Ensure that the origin value is treated as a string

src/components/SearchResult/SearchResult.js
Fixes: 
https://trello.com/c/7sShPr8H/1037-new-ui-search-broken-when-using-instancesearchtext
To verify: run programmatic single search, you should see results in panel.
co-authored with:
@awy3 @DustinRiley
=> Show results for single search

src/apis/loadDocument.js, src/helpers/loadDocument.js
Set custom decrypt function if passed. 
Fixes:
https://support.pdftron.com/a/tickets/14451
=> Set custom decrypt function if passed

src/apis/loadDocument.js, src/helpers/loadDocument.js
* Set custom decrypt function if passed
=> Set custom decrypt function if passed (#689)

src/core/eventListener.js
Update fileAttachmentDataAvailable to be from annotManager in EventToObjectMap
=> Update fileAttachmentDataAvailable to be from annotManager

src/apis/downloadPdf.js, src/core/exportAnnotations.js, src/helpers/downloadPdf.js
See
https://github.com/XodoDocs/webviewer/pull/1347
=> Add options to export annot

src/components/Note/Note.js
https://stackoverflow.com/questions/48454865/onclick-event-of-nested-react-component-is-not-firing-with-firefox-or-ie11
https://trello.com/c/6YXVWqO8/1067-ie11-new-ui-cant-interact-with-note-in-note-panel
=> Fixed issue with note panel in ie11

src/components/Accessibility/Accessibility.js
dont show in accessibility header
See https://github.com/PDFTron/webviewer-ui/pull/712#issuecomment-652586177
=> When notes panel disabled (#712)

src/apis/downloadPdf.js, src/core/exportAnnotations.js, src/helpers/downloadPdf.js
https://github.com/PDFTron/webviewer-ui/pull/695
=> Add options to export annot (#695)

src/event-listeners/onPageComplete.js
Also positioned absolute with full height for better focus alignment.
=> fix: adjusted text pages to new indexing

src/components/WarningModal/WarningModal.js
=> [7.0] [Bugfix] Fixed warning modal staying open after loading another document

src/components/ViewControlsOverlay/ViewControlsOverlay.js
One of the parts of https://trello.com/c/xJnkKzfd/1022-annotationviewstatetestts-is-failing-for-a-strange-reason#comment-5f0cbda41671111f3a4b8f92
=> Moving the dataElement prop up to be bound to the entire button row

src/components/DocumentContainer/DocumentContainer.js, src/constants/feature.js, src/helpers/createFeatureAPI.js, src/redux/actions/internalActions.js, src/redux/initialState.js, src/redux/reducers/viewerReducer.js, src/redux/selectors/exposedSelectors.js
Added capability to disable the mousewheel zoom.
https://support.pdftron.com/a/tickets/14930
https://trello.com/c/pMfbUglx/645-new-api-to-override-mouse-wheel
Once this gets reviewed and approved I will make the PRs to other repos.
=> Add capability to disable mouse wheel zoom

src/components/Choice/Choice.js
=> fix(Choice): may not have dataElement

.prettierrc.json, src/components/Accessibility/Accessibility.js, src/components/Accessibility/Accessibility.scss, src/components/Note/Note.js, src/components/NotesPanel/NotesPanel.js, src/components/SearchOverlay/SearchOverlay.js, src/helpers/hotkeysManager.js
=> feat: updated a11y component

src/components/AnnotationContentOverlay/AnnotationContentOverlay.js
See https://github.com/PDFTron/webviewer-ui/pull/730
=> Render overlay to the left if larger than window

src/components/AnnotationContentOverlay/AnnotationContentOverlay.js
Addresses:
https://support.pdftron.com/a/tickets/12720
=> Render overlay to the left if it gets squeezed when the window is too narrow

src/components/Bookmark/Bookmark.js, src/components/BookmarksPanel/BookmarksPanel.js
=> [7.0] feat: add data-elements to some controls in the bookmark panel

src/helpers/TouchEventManager.js
(cherry picked from commit 469ecdfe5969257ab46f78558355d2fcaf6731f6)
original PR: https://github.com/PDFTron/webviewer-ui/pull/744
=> [legacy/7.0] [Fix] decrease swipe threshold to make swipe more responsive

src/helpers/TouchEventManager.js
(cherry picked from commit 469ecdfe5969257ab46f78558355d2fcaf6731f6)
original PR: https://github.com/PDFTron/webviewer-ui/pull/744
=> [legacy/master] [Fix] decrease swipe threshold to make swipe more responsive

src/helpers/TouchEventManager.js
(cherry picked from commit 469ecdfe5969257ab46f78558355d2fcaf6731f6)
original PR: https://github.com/PDFTron/webviewer-ui/pull/744
=> [7.0] [Fix] decrease swipe threshold to make swipe more responsive

package.json, src/helpers/setupI18n.js
=> [7.0] Changed i18next XHR backend to HTTP

src/components/StyleOption/StyleOption.scss, src/components/StylePopup/StylePopup.js
=> Add back style dropdown for rectangles

i18n/translation-de.json, i18n/translation-en.json, i18n/translation-es.json, i18n/translation-fr.json, i18n/translation-it.json, i18n/translation-ja.json, i18n/translation-ko.json, i18n/translation-nl.json, i18n/translation-pt_br.json, i18n/translation-ru.json, i18n/translation-zh_cn.json, i18n/translation-zh_tw.json, src/components/PrintModal/PrintModal.js
Add print option annotation for legacy 7.0.
=> Feature/print option annotation for legacy 7.0

i18n/translation-de.json, i18n/translation-en.json, i18n/translation-es.json, i18n/translation-fr.json, i18n/translation-it.json, i18n/translation-ja.json, i18n/translation-ko.json, i18n/translation-nl.json, i18n/translation-pt_br.json, i18n/translation-ru.json, i18n/translation-zh_cn.json, i18n/translation-zh_tw.json, src/components/PrintModal/PrintModal.js
Add print option annotation for legacy UI.
=> Feature/print option annotation for v6.3

src/components/NotesPanel/VirtualizedList/VirtualizedList.js
=> [Bugfix] Fix issue with overlapping comments-for 6.3

src/components/SearchPanel/SearchPanel.scss, src/components/SearchResult/SearchResult.js
css hack based on discussion here:
https://github.com/bvaughn/react-virtualized/issues/1316
=> css hack to fix lag of panel width

src/components/ZoomOverlay/ZoomOverlay.js, src/constants/zoomFactors.js, src/helpers/zoom.js
PR to 7.0. Original PR here https://github.com/PDFTron/webviewer-ui/pull/776
=> [7.0] [BUGFIX] Zoom in and zoom out steps are now more predictable

src/components/AnnotationPopup/AnnotationPopup.js
=> [6.3] [Bugfix] Fixed issue where user could not immediately edit free text in IE11

src/components/AnnotationPopup/AnnotationPopup.js
=> [7.0] [Bugfix] Fixed issue where user could not immediately edit free textin IE11

src/components/Bookmark/EditingBookmark.scss, src/components/BookmarksPanel/BookmarksPanel.scss, src/components/CalibrationModal/CalibrationModal.scss, src/components/LinkModal/LinkModal.scss, src/components/PrintModal/PrintModal.scss, src/components/PrintModal/WatermarkModal/WatermarkModal.scss, src/constants/modal.scss
=> [7.0] [Bugfix] Fixed buttons being cut off in IE11

src/components/MeasurementOverlay/MeasurementOverlay.js
=> [7.0] [Bugfix] Fixed touch errors coming up in IE11 when creating measurement annots

src/components/ThumbnailControls/ThumbnailControls.js
Added data elements for thumb rotate and delete
=> Added data-elements for Thumb Controls

package.json
=> Updated to 6.3.6

i18n/translation-fr.json
=> [6.3] [Update] Update FitToWidth French translation

i18n/translation-fr.json
=> [7.0] [Update] Update FitToWidth French translation

i18n/translation-fr.json
Updated translation for `Fit to Width` based on customer feedback
=> [Update] Update FitToWidth French translation

i18n/translation-pt_br.json
https://support.pdftron.com/a/tickets/15486
=> Adding the zoom marquee pt-br translation

i18n/translation-pt_br.json
https://support.pdftron.com/a/tickets/15486 but also making the translation a bit better
=> Making the pt-br translation for zoom marquee better

i18n/translation-de.json, i18n/translation-en.json, i18n/translation-es.json, i18n/translation-fr.json, i18n/translation-it.json, i18n/translation-ja.json, i18n/translation-ko.json, i18n/translation-nl.json, i18n/translation-pt_br.json, i18n/translation-ru.json, i18n/translation-zh_cn.json, i18n/translation-zh_tw.json, src/constants/sortStrategies.js
You are now able to sort by statuses.
=> [Feature] Sort by statuses

src/apis/index.js, src/apis/print.js, src/apis/printInBackground.js, src/components/MenuOverlay/MenuOverlay.js, src/helpers/hotkeysManager.js, src/helpers/print.js
Added options to print API:
- All pages
- pages to print,
- include comments
- include annotations
Tested with API, print through UI, print through cmd+P using the built version.
=> [Feature] Added options object to print API

src/constants/map.js
=> [7.0] [Bugfix] Fixed UI crash due to undefined icon

i18n/translation-de.json, i18n/translation-en.json, i18n/translation-es.json, i18n/translation-fr.json, i18n/translation-it.json, i18n/translation-ja.json, i18n/translation-ko.json, i18n/translation-nl.json, i18n/translation-pt_br.json, i18n/translation-ru.json, i18n/translation-zh_cn.json, i18n/translation-zh_tw.json, src/components/NotesPanel/NotesPanel.js
=> [Bugfix] Sort By was not translated

i18n/translation-de.json, i18n/translation-en.json, i18n/translation-es.json, i18n/translation-fr.json, i18n/translation-it.json, i18n/translation-ja.json, i18n/translation-ko.json, i18n/translation-nl.json, i18n/translation-pt_br.json, i18n/translation-ru.json, i18n/translation-zh_cn.json, i18n/translation-zh_tw.json, src/components/App/App.js, src/components/Choice/index.js, src/components/FilterAnnotMondal/FilterAnnotModal.js, src/components/FilterAnnotMondal/FilterAnnotModal.scss, src/components/FilterAnnotMondal/index.js, src/components/NotesPanel/NotesPanel.js, src/components/NotesPanel/NotesPanel.scss, src/helpers/hotkeysManager.js
You can now filter out annotations through UI:
=> [Feature] Added filtering functionality to UI for annots

i18n/translation-de.json, i18n/translation-en.json, i18n/translation-es.json, i18n/translation-fr.json, i18n/translation-it.json, i18n/translation-ja.json, i18n/translation-ko.json, i18n/translation-nl.json, i18n/translation-pt_br.json, i18n/translation-ru.json, i18n/translation-zh_cn.json, i18n/translation-zh_tw.json, src/components/PrintModal/PrintModal.js, src/components/PrintModal/PrintModal.scss
1. Add a feature to allow the user to change the print quality in the print modal
2. Also, run `npm run translation` to update strings
=> [Feature] - Allow the user to change the print quality in the print modal

src/apis/index.js, src/apis/setPrintedNoteDateFormat.js, src/components/PrintModal/PrintModal.js, src/redux/actions/exposedActions.js, src/redux/initialState.js, src/redux/reducers/viewerReducer.js, src/redux/selectors/exposedSelectors.js
=> [7.0] Added new API to set date format of printed notes

src/apis/index.js, src/apis/setPrintedNoteDateFormat.js, src/components/PrintModal/PrintModal.js, src/redux/actions/exposedActions.js, src/redux/initialState.js, src/redux/reducers/viewerReducer.js, src/redux/selectors/exposedSelectors.js
=> [6.3] Added new API to set date format of printed notes

i18n/translation-fr.json
FIx for https://support.pdftron.com/a/tickets/15698 as pointed out by customer.
=> [CHANGE] made fix for french translation for custom rubber stamp

src/apis/index.js, src/apis/setCustomNoteSelectionFunction.js, src/components/DocumentContainer/DocumentContainer.js, src/components/DocumentContainer/DocumentContainer.scss, src/components/Note/Note.js, src/redux/actions/internalActions.js, src/redux/reducers/viewerReducer.js, src/redux/selectors/exposedSelectors.js
Added extra container for hooking in video controls. Added customNoteSelectionFunction api, for running code when selecting a note.
=> [Feature] SetCustomNoteSelectionFunction API

src/apis/setAnnotationContentOverlayHandler.js, src/components/AnnotationContentOverlay/AnnotationContentOverlay.js
=> [7.0] [Update] Changed behavior of annotation content overlay

src/apis/setAnnotationContentOverlayHandler.js, src/components/AnnotationContentOverlay/AnnotationContentOverlay.js
=> [6.3] [Update] Changed behavior of annotation content overlay

src/components/NoteContent/NoteContent.js, src/components/NotesPanel/VirtualizedList/VirtualizedList.js
=> [Bugfix] Order by time 6.3

src/apis/setActiveHeaderGroup.js, src/apis/setHeaderItems.js, src/helpers/setToolModeAndGroup.js
=> [Bugfix] Fix crashing when selecting tool from right click for 7.0

src/components/AnnotationContentOverlay/AnnotationContentOverlay.js
PR to 6.3; already reviewed in https://github.com/PDFTron/webviewer-ui/pull/858
=> Add open/close capabilities to Annotoverlay

i18n/translation-ja.json
This pull request is related to #905 #906 .
I would like to deploy the same translation fix to v7.3.
Could you please merge it?
=> Fix Japanese translation to 7.3

i18n/translation-ja.json
=> Fix Japanese translations

i18n/translation-ja.json
Hi,
I have fixed Japanese translations.
Could you please approve my pull request if there's not something wrong?
Best regards,
Ryosuke
=> New Japanese Translation Fixed

i18n/translation-ko.json
* Update translation-ko.json
Cherrypick of https://github.com/PDFTron/webviewer-ui/pull/977
=> [Misc] Update translation (#977)

i18n/translation-fr.json
=> Fix several incorrect French translation

package.json, src/components/MenuOverlay/MenuOverlay.js, src/components/NoteHeader/NoteHeader.js, src/components/NoteTextarea/CommentTextarea/CommentTextarea.js, src/helpers/print.js
Manual copy from latest WebViewer 10.1
=> Update for v10.1.1

README.md, i18n/translation-ja.json
Japanese translation errors have been corrected.
=> Japanese translation

i18n/translation-sv.json
Hi!
I have corrected some Swedish translations.
=> Correct some Swedish translations
