PDFTron/webviewer-ui

- src/helpers/downloadPdf.js
- src/helpers/loadDocument.js
If there is file name or path specified then the document won't be able to be loaded. This just makes sure that an error isn't thrown when trying to get the extension.
Also made the default download name a bit nicer, document vs myDocument.
> Load local doc no filename

- src/redux/actions/exposedActions.js
The details of the event include the element itself and the new visibility of that element.
This brings back an event present in the legacy ui for reacting to UI changes (i.e. opening and closing the sidebar)
Issue was reported in the google group: https://groups.google.com/forum/#!topic/pdfnet-webviewer/wt20LMXOSpU
> [update] Fires events when the visibility of an element changes

- src/apis/index.js
- src/apis/setNoteDateFormat.js
- src/components/NoteReply/NoteReply.js
- src/components/NoteRoot/NoteRoot.js
- src/index.js
- src/redux/actions/exposedActions.js
- src/redux/initialState.js
- src/redux/reducers/viewerReducer.js
- src/redux/selectors/exposedSelectors.js
This adds the public API function `setNoteDateFormat` for customizing the date format string used for the creation date of annotations and replies.
This is especially useful for customers of different locales as its possible to choose an appropriate format string.
`readerControl.setNoteDateFormat('DD.MM.YYYY HH:MM')`
Please let me know if the name of the API should be altered or if there is a better way to add such API.
Thanks for reviewing this PR :)
> [update] Allows for custom annotation date format

- src/components/PageNavOverlay/PageNavOverlay.js
- src/event-listeners/onBeforeDocumentLoaded.js
- src/event-listeners/onLayoutChanged.js
- src/helpers/getDefaultPageLabels.js
This pull request is to fix issue #66 . The solution was:
- Change the way we were setting the 'isCustomPageLabels' variable (check if any custom labels are being used)
- Updated the 'onLayoutChanged' event to dispatched the 'setPageLabels' action. For '.pptx' and '.docx' file, the page count (and page labels created) were incorrect during the "onDocumentReady" event but should be correct when the 'onLayoutChanged' trigger.
> [bugfix] fixes #66

- src/redux/actions/exposedActions.js
Looks like for a previous fix( for #47 ) we added the 'fireEvent' call to the "openElement" action. Since we didn't want to do a lot of unnecessary 'fireEvent' calls we tried to filter them out. The filter for unnecessary calls seem to be breaking the annotation popup comment button. 
The fix is to not filter out events for the left panel if the left panel isn't open yet.
> [bugfix] Fix #69 by checking if left panel is opened yet

- src/components/AnnotationPopup/AnnotationPopup.js
Updated the 'componentDidUpdate' of the AnnotationPopup to have it open on mouse up when needed. Before it only open when a new annotation was selected.
> [update] Resolves #62 by having annotation popup reappear on mouse up

- src/helpers/setupLoadAnnotationsFromServer.js
If the annotations have already been loaded from the server then we can just return an empty string which will continue on the annotation loading process
> Fix issue where the annotationsLoadedPromise never resolves

- src/components/HeaderItems/HeaderItems.js
Continue to use i for now when data element isn't defined
> Fix issue with header items remounting more than necessary

- i18n/translation-nl.json
One key was missing in the Dutch translation file, so added that key.
> Added translation for missing key

- src/components/AnnotationPopup/AnnotationPopup.js
- src/components/PrintModal/PrintModal.js
If the annotation popup was visible when the document was unloaded then the AnnotationPopup retained the state about the selected annotation
This could cause errors if an event came in and the popup thought that an annotation was selected
> Fix issue with updateAnnotationPermission events triggering when document is unloaded and annotation was previously selected

- src/helpers/loadDocument.js
Bug fix for
https://trello.com/c/ykBx8rJC/118-2-provide-webviewerjs-constructor-option-for-xod-cache-hinting
The cache hinting was causing problems with CloudFront for xod files so we were thinking of giving a constructor option for setting it. However we (me and Matt) decided to just set the default to 'NO_HINT' for now and not have an option for setting cache hinting unless someone asks for it.
Below is an example of network calls with and without cache hinting:
> [BugFix]Update load document caching

- src/apis/enableAnnotations.js
- src/apis/enableRedaction.js
- src/components/RedactionOverlay/RedactionOverlay.js
- src/helpers/setDefaultDisabledElements.js
- src/redux/actions/internalActions.js
- src/redux/initialState.js
This commit is to fix some bugs where enabling/disabling tools was doing odd things (only enabling redactions). The big change that might cause issues is, I noticed in disableAnnotation.js we were doing 
`  getAnnotationCreateToolNames().forEach(toolName => {
core.getTool(toolName).disabled = true;
});`
However we aren't enabling them in enableAnnotation.js (I added it in this commit)
> [bugfix] Fix issues with enabling/disabling tools causing unexpected results

- src/helpers/applyRedactions.js
This is kind of an band aid fix for IE. Since IE is slow, the user might press "Apply" more than once which throw an error. A better solution for later would be to show the 'loadingModal' till the promise from 'applyRedactions' is resolved, but I was having problem getting that to work. So for now, it'll just close the warning message right away
> [Bugfix] Fix problem with redaction in IE

- src/components/Note/Note.js
- src/redux/selectors/exposedSelectors.js
Updated notes to scroll into view when the related annotation is selected.
Only triggers when a single annotation is selected.
> [update] auto notes scrolling

- src/index.js
Use 'initPDFWorkerTransports' instead of 'preloadPDFWorker' so that the 'pdfnet.res' file get loaded. 'initPDFWorkerTransports' actually calls 'preloadPDFWorker' if it hadn't been called yet so this should be safe.
> [update]Preload update

- src/components/PrintModal/PrintModal.js
Before we were assuming annotation icons are in the assets folder. However users are able to create custom annotations/tools which use an inline svg or base64 image
> [bugfix] Fixed issue where printing comments will error if the icon is an inline svg or an image

- src/components/Thumbnail/Thumbnail.js
- src/components/Thumbnail/Thumbnail.scss
- src/components/ThumbnailsPanel/ThumbnailsPanel.js
This pull request is for fixing two thumbnails bugs. They are:
**annotation canvas being bigger then page canvas**
Steps to reproduces: 
- Set the browser zoom to less then 100% and load a viewer
- Open a pdf (not xod or office file, thumbnails would be an IMG instead of an canvas)
- Annotation canvas would be larger then page canvas so any annotation on it would be off
Solutions:  Removing the 'width/height: auto !important;' in the css fix this issue. Only problem is 'auto !important' is needed for xod files in IE (why I have a media query that only affect IE, this problem still exists in IE).
**Rotating the document data doesn't rotate the thumbnail**
(this bug was reported in #143)
If the users run something like 'readerControl.docViewer.getDocument().rotatePages([1], 1)' the document …
> [bugfix] Fix annotation and rotation bugs for thumbnails

- src/components/RedactionOverlay/RedactionOverlay.scss
Small fix for the redaction icon. The inside "lines" weren't being set to the same style as the other lines
Another fix would be update "Icon.scss" to set all fill to be whatever 'var(--icon-color)' is
> [Bugfix] Fix redaction style

- src/apis/index.js
- src/apis/showErrorMessage.js
- src/components/ErrorModal/ErrorModal.js
- src/index.js
Triggers a 'customErrorMessage' event to get the error modal to display with the provided error message. This was to avoid other handlers of 'loaderror' to not trigger when there is no actual load error.
> Basic error modal API

- src/apis/showErrorMessage.js
- src/components/ErrorModal/ErrorModal.js
- src/index.js
- src/redux/actions/exposedActions.js
- src/redux/reducers/viewerReducer.js
- src/redux/selectors/exposedSelectors.js
Fixed issue where the API is called before the component was able to mount. Now the modal depends on redux to get the error message. Previous implementation still works but instead of setting local state, the redux state is updated instead.
> [bugfix] changed error modal API to use redux instead of events

- src/components/SignatureModal/SignatureModal.js
If the signature modal is disabled to start, the signature canvas is never setup due to the canvas reference never being set. Enabling the modal afterwards also gives an error since the signature tool was not initialized.
The solution to the missing canvas was to ensure that the initial setup of the signature canvas is skipped if the canvas did not render. The solution to enabling an initially disabled signature modal was to perform the setup if the modal was enabled and setup hasn't been performed at least once.
> [bugfix] fixed issue with enabling & disabling the signature modal

- src/redux/actions/internalActions.js
Transforms non-array parameters in `addItems`, `removeItems` and `setItems` APIs to appropriate arrays.
> [update] Allows non-array parameters for header API

- assets/ic_group_button_24px.svg
- src/components/GroupButton/GroupButton.js
Sets default group button icon to default group icon when `img` is unspecified and group contains buttons other than tool button. Also generates a warning message on the console.
> [update] Set default group button icon when img is unspecified and group contains buttons other than tool button

- src/helpers/setupLoadAnnotationsFromServer.js
The code in 'setupLoadAnnotationFromServer.js' is calling the callback function multiple times.  When it fails once, it calls the callback because of the "window.readerControl.serverFailed" being true and again below in the AJAX call. 
The problem is that in the core, "DocumenViewer.finishLoadingLastAnnotations" get called twice so it'll end up trying to load the next part of the file twice. This will fail for XOD files.
> [bugfix] Fix for server URL with XOD

- src/event-listeners/onDocumentLoaded.js
- src/index.js
fixes #185 
Moved changing fitMode to happen before ready event is triggered. So that it can be set by users after the ready event.
> fixes #185 

- src/index.js
Merge in changes from #271
Only different was I got rid of the 'version.slice(0, -6);' at the top
I was thinking of doing something like 
```
const [ coreMajorVersion, coreMinorVersion,, coreCommitVersion ] = coreVersion.split('.');
const [ uiMajorVersion, uiMinorVersion ] = uiVersion.split('.');
if(coreCommitVersion) { // we don't want commit version anymore
coreVersion = coreVersion.slice(0, -(coreCommitVersion.length + 1));
}
```
Let me know if I should I add it
> [Update] Merge in change for version checking

- src/components/ThumbnailsPanel/ThumbnailsPanel.js
Thumbnails were not updated when annotations were hidden or unhidden.
> Update thumbnails when annotation visibility toggled

- src/components/NotesPanel/NotesPanel.js
Changed notes panel to render hidden annotations as real, hidden note components. This should reduce the performance hit when hiding and unhiding a bunch of annotations. The issue impacts FireFox (~6s), Edge (a long time), IE (a long time), and Safari (~2s).
Fixes #264
Before
After
> Performance update for hidden notes

- src/components/ToolStylePopup/ToolStylePopup.scss
Changed z-index of ToolStylePopup to match `overlay.scss` and prevent `leftPanel` from covering the popup.
> [bugfix] resolves #289

- src/components/RedactionOverlay/RedactionOverlay.js
- src/redux/initialState.js
Before  `readerControl.disableElement('applyAllButton')` didn't work. At some point, I'm going to remove 'RedactionOverlay.js' and make it like the other headers (wasn't possible before but it is now).
> [bugfix]Fix 'disableElement' being used be with redaction

- i18n/translation-de.json
With your translation it looks like this:
After the changes it looks like this.
I am German so, I hope you trust me with the syllable division ;-)
> Fix how searching case sensitively is displayed in German ui

- src/event-listeners/onKeyDown.js
Disabling the signature tool and pressing the shortcut key generates an error. Added a check to ensure the data element exists before attempting to trigger the tool.
> Fixed error using shortcut key while signature tool is disabled

- src/components/PrintModal/PrintModal.js
An update for printing when in 'double' or 'cover' mode where we want to print both pages when the users select "current" when printing
> [Feature] Update print for double and cover mode

- src/components/ToolGroupButton/ToolGroupButton.js
- src/redux/selectors/exposedSelectors.js
While the code to disable tools works, the tool group buttons were not determining whether all the tools underneath them were all disabled properly.
This fix applies the fix from the dev branch: b10aa6d55587cd81c30edbc9e588198e4f0d733e.
> [BugFix] Applied fix for tool groups being visible during readonly mode

- src/components/Note/Note.js
fix for crash when noteReply is disabled and trying to write a comment
> [BugFix] fix for crash when noteReply is disabled and trying to write a comment

- src/components/SearchOverlay/SearchOverlay.js
When you search for text that doesn't exist, it doesn't clear the current result
i.e. "Revision" stays highlighted even when searching for something that doesn't exists
> [Bugfix] Clear current highlight text when new search is invalid

- src/components/NoteContent/NoteContent.js
Currently every render of the `NotesPanel` component will rerender all the `NoteContent` components. This is because the `NoteContent` component uses `useContext` and the `NotesPanel` always passes a new object(with same properties and values, but different reference) to the context on every render.
The rerender will become expensive when there're many `NoteContent` components because the component uses `Autolinker.link`, which takes some time to execute.
This PR uses the option 3 in https://github.com/facebook/react/issues/15156#issuecomment-474590693 to improve the performance.
Note that this is not the ideal solution. We can potentially stop the `NotePanel` component from passing a new context reference on every rerender. But this involves some work.
> [upgrade] Use useMemo for the NoteContent component

- src/helpers/documentContainerHelper.js
If a user clicks the top right note panel () or programmatically use "readerControl.setSideWindowVisibility()" quickly, the document with drift around.  You don't see this if you use it like a normal person
You can reproduce it here 
https://www.pdftron.com/samples/web/samples/viewing/viewing/
What it does depends on your zoom level and the size of the browser window. 
UPDATE: read below comment
> [Bugfx] Fixed issue with document drifting around in IE and Edge

- src/components/Note/Note.js
- When placing a comment, comment box will be focused and a reply will be hidden
- For readonly annotations, reply will be the default action
> Improved commenting behaviour

- src/index.js
fix is related to this bug https://trello.com/c/s4b58qPv/550-the-preloadworker-option-and-using-setpdfworkerpath-do-not-work-together-well
The "preloadWorker" option used to load workers beforehand and setPDFWorkerPath, (and other set path functions) is used in config file. WebViewer will try to load workers first and after that process config.js file. And WV loads workers from the wrong location since setPDFWorkerPath is processes later
> [bugfix] fix worker loading after config.js is loaded

- src/components/App/App.js
`ControlUtils.byteRangeCheck` was missing and thus causing encrypted XODs to fail to load when the encryption object was provided. It was falsified to return 206 since `loadDocument` now does the range check. It should be kept to keep compatibility with the legacy UI for now.
> [bugfix] Fixed loading encrypted XOD through constructor

- src/components/PrintHandler/PrintHandler.scss
- src/components/PrintModal/PrintModal.js
- src/helpers/device.js
- src/helpers/print.js
- src/redux/selectors/exposedSelectors.js
Safari does weird stuff when printing when printing with a small screen (can either use an iPhone or just resize the window). Trying to set the "width" to something doesn't fix it, but we can use the hack in this fix. Also when using Chrome on iOS, `document.execCommand('print')` return true even when it doesn't do anything ( need to use `window.print()`).
> [Bugfix] Fix printing issue on iOS/Android

- src/components/SignatureModal/SignatureModal.js
For a ticket a  customer was saying the signature canvas clear when the screen rotate (I'm guessing they are on a mobile device), so I made it redraw after it get clear.  
Another solution would be do something like
```
const image = new Image();
const ctx = canvas.getContext('2d');
image.onload = function() {
ctx.drawImage(image, 0, 0);
};
image.src = canvas.toDataURL();
```
This might be good if we don't want to use "signatureTool.drawAnnot"
> [Bugfix] Redraw signature canvas on resize or rotate

- src/components/PrintModal/PrintModal.js
Fix for ticket: https://pdftron.freshdesk.com/a/tickets/9342
It seems when the  "get annotation display author name" function is overrided, it's not shown correctly in the print modal.
> Bug fix/show correct annotation author on print

- src/components/ThumbnailsPanel/ThumbnailsPanel.js
Fix for ticket: https://pdftron.freshdesk.com/a/tickets/9383
Error was something along the lines of:
CellSizeAndPositionManager.js:66 Uncaught (in promise) Error: Requested index -1 is outside of range 0..0
It came from thumbnail panel which used the react virtualized list.
For reference, it looks like a known opened issue:
https://github.com/bvaughn/react-virtualized/issues/1016
> Ensured that row count is always an integer

- src/helpers/downloadPdf.js
I noticed with larger files (10+MB 100+ pages), `core.exportAnnotations()` might take 10+ seconds, so I was thinking we should open the loading indicator before that instead of after
> [Bugfix] Loading indicator during download

- src/helpers/documentContainerHelper.js
If you hide the header (`readerControl.closeElement('header')`), there is a small gap at the bottom when using Edge or IE
The issue is `documentContainer` should have a 'no-header' class (like what Chrome and other browsers are getting) instead of a 'full-height' class. I'm not sure if 'full-height' is a class we removed because it currently doesn't do anything.
> [Bugfix] Fixed incorrect class name in Edge/IE

- src/components/PrintModal/PrintModal.js
- src/components/SearchOverlay/SearchOverlay.js
- src/components/SearchPanel/SearchPanel.js
- src/components/SearchPanel/SearchPanel.scss
Received a [support ticket ](https://support.pdftron.com/a/tickets/10205)requesting the ability to disable the wildcard search option in the search panel. It's not straightforward to do it purely in CSS by the customer so I have added it as a `data-element` that can be disabled. Tweaked some CSS to make sure spacing is consistent when this option is disabled. 
UPDATE:
- Also added `applyWatermark` as data-element (this was removed 20 days ago in [master](https://github.com/PDFTron/webviewer-ui/pull/432/files#diff-e401c1d7d855d5dd2d33eaf5b014ffecL543)
QA Steps:
Disable the `wildCardSearchOption` and `applyWatermark` in your env:
```
Webviewer({
initialDoc: hashFile,
path: '/lib',
disabledElements: ['wildCardSearchOption', 'applyWatermark'],
enableMeasurement: true,
}, …
```
> [FIX]Add option to disable wild-card-search in search panel and applyWatermark in print panel

- src/apis/updateElement.js
- src/components/Button/Button.js
- src/components/ColorPalette/ColorPalette.js
- src/components/ColorPalette/ColorPalette.scss
- src/constants/styles.scss
- src/redux/initialState.js
- src/redux/selectors/exposedSelectors.js
QA:
- In the console, do `readerControl.updateElement('colorPalette', ['#FFFFFF'])`
- Now the palette should only contain the white color
This is a request from a customer who wishes to customize the colors that are available in the color palette.  There're some noises in this PR since I formatted the component using Prettier, and there're some refactoring as well. I have to do some refactoring because the previous implementation has some hardcoded values that don't work well anymore when users are able to customize the colors.
> [CHANGE] Allow instance.updateElement to change the colors in the color palette

- src/components/SignatureModal/InkSignature/InkSignature.js
I updated the logic for how we redraw the signature.  I move some of it into the core (since  the core has a reference to the canvas). The PR for the core is 730, and has been merge in. 
One thing that I wanted to ask (not sure if it's too late) was if it make sense to call the method "resizeCanvas", since it could also be called "SignatureCreateTool.resizeAndRefreshCanvas" or even "SignatureCreateTool.refreshCanvas".
> [Bugfix] Redrawing signature on resize

- src/components/Thumbnail/Thumbnail.js
There seem to be a race condition where there is a layout change event that trigger before the initial thumbnail is loaded. This produced a `parameter 1 is not of type Node` error, I added a null check to fix this issue. To reproduce it you can use
```
Webviewer({
// this error doesn't happen for every file but it seems to consistently fail for this file 
initialDoc: 'https://pdftron.s3.amazonaws.com/files/Boro.pdf',
pdftronServer: 'https://demo.pdftron.com/',
path: '/lib',
})
```
> [Bugfix] Thumbnail loading when using WebViewer server

- src/components/ErrorModal/ErrorModal.js
The error message was changed from a string to an object in a PR in the core. The error modal will need to know how to get the message and display it by default.
> Changed error modal for upcoming error info changes

- src/components/DocumentContainer/DocumentContainer.js
- src/helpers/TouchEventManager.js
- src/helpers/getNumberOfPagesToNavigate.js
- src/helpers/hotkeysManager.js
- src/helpers/setCurrentPage.js
I fix a few issues with page scrolling with the arrow keys and the pageup/pagedown buttons. Problems I fix were
- Up/Down arrow keys will stop working when switching pages if you are zoomed in 
- For non-continuous mode with 2 pages, the mouse scroll wheel will go up and down while the up and down arrow keys will switch between right and left
Note sure if we want:
Should page up/down key change one page at a time when displaying two pages? When the user is zoomed out it doesn't make sense to do one page at time since going from page 3 to 4 might not do anything (if they are both displayed). However when WebViewer is zoomed in, the page up/down key will go from the left to right which make sense but feel unnatural since most of the time page up/down only does vertical moment.
> [Bugfix] Keyboard page scrolling fixes

- src/components/SearchOverlay/SearchOverlay.js
- src/components/SearchPanel/SearchPanel.js
- src/components/SearchPanel/SearchPanel.scss
- src/core/eventListener.js
- src/redux/actions/internalActions.js
- src/redux/reducers/searchReducer.js
- src/redux/selectors/exposedSelectors.js
Fixes the issue for invalid regex in search
Regex in Chrome 
```js
readerControl.searchTextFull('(?<=(PDF\\s))(\\w+)', { regex: true }); // Valid 
readerControl.searchTextFull('(?=(PDF\\s)(\\w+)', { regex: true }); // Invlaid
```
Regex in Firefox
```js
readerControl.searchTextFull('(?<=(PDF\\s))(\\w+)', { regex: true }); // Invalid
readerControl.searchTextFull('(?=(PDF\\s))(\\w+)', { regex: true }); // Valid
readerControl.searchTextFull('(?=(PDF\\s)(\\w+)', { regex: true }); // Invalid
```
Fixes https://trello.com/c/Sk4OW3BR/767-invalid-regex-in-search-throws-error-and-gets-stuck
> [Bugfix] fixes the issue for invalid regex in search

- src/components/LeftPanel/LeftPanel.js
- src/components/ThumbnailControls/ThumbnailControls.js
- src/components/ThumbnailsPanel/ThumbnailsPanel.js
- src/redux/actions/exposedActions.js
- src/redux/reducers/viewerReducer.js
This pull request is for allowing users to hold "Ctrl" to drag and drop multiple thumbnails at once (will be needed for the next update).  Also I clean up the code by using the "LayoutChanged" event to updated the selected thumbnails.
> [Update] Thumbnail multi drag and cleanup

- src/event-listeners/onUpdateAnnotationPermission.js
- src/helpers/createFeatureAPI.js
This PR fix an issue where the "link" button is appearing when annotations are disabled. 
You can test with:
`readerControl.setReadOnly(true)`
`readerControl.disableAnnotations()`
> [Bugfix] Hide links when other annotations are disabled

- src/helpers/downloadPdf.js
When includeAnnotations was false the original annotations
still appeared. It appears we need to pass an empty xfdf
string to make sure that no annotations show up.
Also made it to so that exportAnnotations isn't called
in this case or an overriding xfdfString is passed
> Fix issue with annotations still appearing in downloaded PDF

- src/components/CustomElement/CustomElement.js
- src/components/Tooltip/Tooltip.js
This fix allows tooltip to work for customElements. So you can do something like 
```
Webviewer({}, document.getElementById('viewer')).then(instance => {
var checkboxLabelElement = {
type: 'customElement',
title: 'Tooltip popup message',
render: function() {
const label = document.createElement('label');
label.innerHTML = 'Custom Label';
return label;
},
};
instance.setHeaderItems(function(header) {
var items = header.getItems();
items.splice(items.length - 2, 0, checkboxLabelElement);
header.update(items);
});
/*
```
and you'll get the tooltip when you hover over the element. 
Also for "intialState.js" we can add a title for "zoomOverlayButton" and maybe clean up "signatureToolButton" (SignatureToolButton.js is adding the tooltip for signature).
> [Bugfix] Allow tooltip to work for customElement headers

- src/helpers/loadDocument.js
This is the UI side for loading office documents as pdfs. After this, you can just add 
` loadAsPDF: true,` into the WebViewer constructor options and it'll work
> [Feature] Option for loading office file as pdf

- src/components/MeasurementOverlay/LineMeasurementInput.js
This was because of the timing of how redrawAnnotation was called
after the annotation was deleted which made it incorrectly stick
around as the pending annotation. Using drawAnnotations will not
cause this problem.
> Fix issue where line measurements would be visible after deleting

- src/components/Thumbnail/Thumbnail.js
- src/components/ThumbnailsPanel/ThumbnailsPanel.js
Fixed some issues with how thumbnails are rendering. Issues fixed are
- Show current annotations for the initial load of the thumbnail panel
- Update thumbnails after applying redaction or pages operation (move, insert, delete, rotate)
> [Bugfix] Thumbnail update rendering fix

- src/components/AnnotationPopup/AnnotationPopup.js
We can style grouped annotations.
It doesn't quite match Adobe's, but it should be intuitive enough.
Assuming an annotation is grouped, if you click on it and style it, it will only style the annotation you clicked on.
This feature was requested by a customer.
If we go Adobe's way, it may take a bit more time with implementation
> [CHANGE] can style grouped annotation

- src/components/AnnotationContentOverlay/AnnotationContentOverlay.js
Checks if the mouse in moving on a modal component to decide if we are hovering on an annotation. Fixes #570.
> [CHANGE] fix(AnnotationContentOverlay): do not show the component when a modal is open

- src/components/DocumentContainer/DocumentContainer.js
If you change WebViewer to display a single page only, and scroll left to right slowly on a trackpad, it'll randomly jump to page two. You can use the following document to test
[pageRatio.xlsx](https://github.com/PDFTron/webviewer-ui/files/4512149/pageRatio.xlsx)
I tested this on an old macBook and see that the "e.deltaY" will be between -1 and 1  when doing horizontal scrolling which cause the page to change.
> [Bugfix] Fix scrolling with track pad changing pages

- src/apis/index.js
- src/apis/setActivePalette.js
- src/apis/setColorPalette.js
- src/apis/updateElement.js
- src/components/ColorPalette/ColorPalette.js
- src/components/ColorPaletteHeader/ColorPaletteHeader.js
- src/components/StylePopup/StylePopup.js
- src/redux/actions/internalActions.js
- src/redux/reducers/viewerReducer.js
`setActivePalette` allows users to programmatically set the active color palette for a tool and its annotations.
`setColorPalette` allows users to set different colors for all of the tools or specific tools.
```javascript
instance.setColorPalette(['#FFFFFF', '#001133', '#DDDDDD', '#12345D']);
instance.setColorPalette({
toolNames: ['AnnotationCreateRectangle', 'AnnotationCreatePolygon'],
colors: ['#FFFFFF', 'transparency', '#000000'],
});
instance.setColorPalette({
toolNames: ['AnnotationCreateFreeText'],
colors: ['#000000'],
});
```
> feat(api): add setActivePalette and setColorPalette APIs

- src/components/ThumbnailsPanel/ThumbnailsPanel.js
When dragging the thumbnail panel, the thumbnails don't seem to be rendered like a grid when its dragged to its max width. it still stays as 1 column. Only when you resize the browser, it will happen.
Made change so that it can have 1-3 depending on the thumbnail width without resizing the browser.
Adobe seems to have this kind of feature.
> [CHANGE] able to show thumbnails like a grid on drag of thumbnail panel

- src/helpers/hotkeysManager.js
- src/helpers/setToolModeAndGroup.js
After the signature pop up show up, users can use hot keys to change the current tool. So it's possible for the signature modal to be displayed when the active tool has been change. If the user than click "create", there will be a signature preview even when the tool has already changed
My fix disable changing tools when the signature overlay is opened. I don't think there are any other cases similar to this one (is there?)
> [Bugfix] Stop signature from entering into an error state 

- src/components/MeasurementOverlay/EllipseMeasurementOverlay.js
- src/components/MeasurementOverlay/LineMeasurementInput.js
Mobile device will bring up the keyboard when an input is focused. This will shift the document container up and make it harder to finish creating an annotation.
@bollain  Let me know if this is ok. The lint is failing which I will fix soon!
> fix(MeasurementOverlay): only focus the input element when it's not a mobile device

- src/components/FilePickerHandler/FilePickerHandler.js
I noticed that when using WebViewer Server, some of the allowed file formats weren't showing up.  By the way, is there a nicer way to know if WebViewer Server is being used?
> [Bugfix] Changed allowed file format

- src/apis/disableTools.js
@achenPDFTron Hopefully this clears things a bit, let me know if you have any suggestions.
> doc: explicitly mention that disableTools uses disableElements internally, and state the difference between them

- src/helpers/setDefaultDisabledElements.js
- src/redux/initialState.js
Same as #608 , enable selecting pages and the "document controls" by default
> [Update] Enable selecting thumbnails by default

- src/helpers/getOverlayPositionBasedOn.js
This is for this bug
https://trello.com/c/YSdveJrl/1021-ui-releated-bug-signature-overlay-is-off
We prevent the header from having a left offset that is negative so it won't go offscreen
> [Bugfix] Fix header overlay being offscreen

- src/apis/mentions.js
- src/components/Note/ReplyArea/ReplyArea.js
- src/components/NoteContent/ContentArea/ContentArea.js
- src/components/NoteContent/NoteContent.js
- src/components/NoteTextarea/AutoResizeTextarea/AutoResizeTextarea.js
- src/components/NoteTextarea/MentionsTextarea/MentionsTextarea.js
- src/components/NoteTextarea/NoteTextarea.js
- src/helpers/MentionsManager.js
- src/redux/selectors/exposedSelectors.js
1. fixes #604 - Mentions should use a unique ID for selection. This issue is fixed by adding user ids to annotations' custom data, and retrieve them instead of user values(names) to determine when mentions have been added/modified/deleted.
2. fixes an issue where deleting a mention in the editing mode didn't delete the whole mention at once. This issue was caused by us just passing the plain text value to the mentions input, where the text with markup should be passed to it
> fix: 2 issues with mentions

- src/constants/quill.scss
This would happen because the clipboard became focused and was far off to the left of the page
> Fix issue where pasting into a freetext when zoomed in would scroll the viewer to the left

- src/components/MeasurementOverlay/CustomMeasurementOverlay.js
- src/components/MeasurementOverlay/EllipseMeasurementOverlay.js
- src/components/MeasurementOverlay/MeasurementOverlay.js
- src/components/MeasurementOverlay/MeasurementOverlay.scss
The purpose of this PR is to address the second feedback from https://github.com/PDFTron/webviewer-ui/issues/610.
This PR does two things:
1. Make the measurement overlay component draggable, so users will be able to move it around in the view to find a comfortable spot.
2. Make the component transparent when
- we are creating an annotation and our mouse is hovering the component
- we are selecting an annotation and our mouse is hovering on the part of the annotation that's under the component
Before this PR, a user won't be able to create a path point under the component for polyline and polygon annotations, which I see can be a bit annoying.
Also some of the code is formatted.
@bollain Could you take a look when you have time? Just want to see if you have any feedback.
> feat(MeasurementOverlay): allow creation and editing measurement annotations underneath the measurement overlay

- src/apis/index.js
- src/apis/setAnnotationContentOverlayHandler.js
- src/components/AnnotationContentOverlay/AnnotationContentOverlay.js
- src/redux/actions/exposedActions.js
- src/redux/initialState.js
- src/redux/reducers/viewerReducer.js
- src/redux/selectors/exposedSelectors.js
Trello card:
https://trello.com/c/OsViPPT3/906-custom-tooltips
Adds new API so users can override current tooltip behaviour on annotations.
API takes a callback that should return a DOM element.
```
Webviewer({
initialDoc: hashFile,
path: '/lib',
}, document.getElementById('viewer')).then(instance => {
instance.setAnnotationContentOverlayHandler(annotation => {
var div = document.createElement("div")
div.appendChild(document.createTextNode(`Created by: ${annotation.Author}`))
div.appendChild(document.createElement('br'))
div.appendChild(document.createTextNode(`Created on ${annotation.DateCreated}`))
return div
})
});
```
> Add API to customize annotation tooltips

- src/components/Slider/Slider.js
- src/components/StylePopup/StylePopup.js
Sliders were provided data-element values but were not actually used. This PR should correct that, as well as a bug where disabling one, would cause the next to render due to a mismatch with the slider prop indices.
I could not wrap the sliders in another element to add this data-element since the elements would then not line up in the grid.
> [6.3][Bugfix] Fixed sliders to use data-element

- src/components/Thumbnail/Thumbnail.js
The problem was that WebViewer Server creates thumbnails larger than the max size
and using max-width, max-height just fits them to a 150 pixel square.
This code should maintain the aspect ratio
> [CHANGE] Fix issue where the aspect ratio of thumbnails wasn't preserved in some cases

- src/components/Thumbnail/Thumbnail.js
The problem was that WebViewer Server creates thumbnails larger than the max size
and using max-width, max-height just fits them to a 150 pixel square.
This code should maintain the aspect ratio
> Fix issue where the aspect ratio of thumbnails wasn't preserved in some cases

- src/components/AnnotationContentOverlay/AnnotationContentOverlay.js
Made some changes based on client feedback. CustomOverlay was re-rendering on every mouseMove, which made jitter as there was an expensive DOM manipulation operation happening everytime.
To fix this, only render the custom overlay once, by making sure the references stay the same.
Also adds a check so CustomOverlays show for text annotations, as the client requests this.
To test:
```
instance.setAnnotationContentOverlayHandler(annotation => {
const div = document.createElement("div")
div.appendChild(document.createTextNode(`Created by: ${annotation.Author}`))
div.appendChild(document.createElement('br'))
div.appendChild(document.createTextNode(`Created on ${annotation.DateCreated}`))
return div
})
```
> Tooltip perf

- src/components/FlyoutMenu/FlyoutMenu.js
leads to a more natural tabbing behavior by moving to the next element on tab (this is more accurate to native dropdown menu behavior as well)
> fix(a11y): remove prevent default in flyout menu

- src/components/ColorPalette/ColorPalette.js
Fixes https://trello.com/c/nTY5SgpH/1008-new-ui-calling-instancesetcolorpalette-will-blow-the-app-up
However, when users customize the pallete for a specific tool, the new UI will still show the default colors 
Do we want to keep this API or how should we approach this?
@khein-pdftron
> Fixed issue with customPalette API

- src/components/Thumbnail/Thumbnail.scss
We're now explicitly setting the size through
JavaScript so this CSS isn't necessary anymore
> Fix issue with the size of thumbnails in IE

- src/components/ColorPaletteHeader/ColorPaletteHeader.js
Simple fix for this issue:
https://trello.com/c/wsByPkDH/992-new-ui-text-in-the-color-palette-is-cut-off-in-different-languages
Now headers are wrapped in tooltips so users can see the full header whenever it is too long to be displayed
> Wrap palette headers in tooltips

- src/components/AnnotationPopup/AnnotationPopup.js
The transform added by react-draggable appears to interfere with our existing style popup at the bottom on smaller mobile screens. This causes it to mount with zero height.
This PR should keep react-draggable but disable it on smaller screens.
> [6.3] [Bugfix] Fixed bug caused by draggable transform conflict

- src/components/SearchOverlay/SearchOverlay.scss
Fixes: https://trello.com/c/bz3yw2IA/1064-ie11-new-ui-cant-type-in-search-panel
The problem:
So in plain words, if somewhere in your CSS you have something like this: flex:1 , that is not translated the same way in all browsers. Try changing it to 1 0 0 and I believe you will immediately see that it -kinda- works.
https://stackoverflow.com/questions/21600345/flexbox-and-internet-explorer-11-displayflex-in-html
> Bug fix/ie 11 search bar

- src/components/Accessibility/Accessibility.js
dont show in accessibility header
Fixes:
https://support.pdftron.com/a/tickets/14757
If WV is in accessibility mode, when the notes panel is disabled, a skip to notes link is still shown to the user. This removes that link if the notes panel is disabled
> When notes panel disabled

- src/apis/setNoteTransformFunction.js
Small update to the example for `dangerouslySetNoteTransformFunction`
The classes used in the note changed with the new UI, so the example used doesn't work anymore and blows up the app.
https://trello.com/c/pRSHYkF5
As a side note - the changing of classes will break the app for anyone still relying on those for querySelectors. How will we communicate this?
> Update to dangerouslySetNoteTransform example

- src/components/Bookmark/Bookmark.js
- src/components/BookmarksPanel/BookmarksPanel.js
This PR is to address the feedback from https://support.pdftron.com/a/tickets/14897
Two new `data-element`s have been added to the bookmark panel, so the client can call `instance.disableElements` to hide them.
> feat: add data-elements to some controls in the bookmark panel

- src/components/WarningModal/WarningModal.js
If you attempt to delete a page, a warning modal will appear. Without closing the modal or selecting an option, load another document, and the modal will remain. Choosing to delete the page will delete the page on the new document.
This PR will fix this issue by closing the modal on `documentUnloaded`.
> [Bugfix] Fixed warning modal staying open after loading another document

- .prettierrc.json
- src/components/Accessibility/Accessibility.js
- src/components/Accessibility/Accessibility.scss
- src/components/Note/Note.js
- src/components/NotesPanel/NotesPanel.js
- src/components/SearchOverlay/SearchOverlay.js
- src/helpers/hotkeysManager.js
1. Simplified a11y component, added jump to search
1. Removed hotkey enter listeners
TO TEST:
1. Run accessibility sample
- Should have helper to skip to sections when you tab into it
- Should skip to sections correctly
1. Notes on annotations should be focusable
- Pressing enter to select a note when tabbed to it should not insert a line break into the comment field
> feat: updated a11y component

- src/helpers/TouchEventManager.js
Changed swipe threshold to 0.1 of page width from 0.35, which seems to most optimal value for user experience.
See:
https://trello.com/c/oOaKumTk/1108-on-continuous-page-mode-swipe-left-and-right-not-registered-always-ios-1351
> [Fix] decrease swipe threshold to make swipe more responsive

- package.json
- src/helpers/setupI18n.js
i18next-xhr-backend is now deprecated. i18next-http-backend is now the recommended replacement.
The usage and API is similar but for our use case, they should be exactly the same.
> Changed i18next XHR backend to HTTP

- src/components/ThumbnailsPanel/ThumbnailsPanel.js
Fixes https://trello.com/c/b5uGPRLW/1152-ie11-not-able-to-drag-and-drop-thumbnail-to-rearrange-pages
Seems its not supported in IE11
https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer
From talking with ANdrew, we will not allow merging documents between viewers in thumbnail panel in IE11.
> Added check to not use getData if in IE11

- src/components/HeaderItems/ToolGroupButtonsScroll.js
https://trello.com/c/85cmruGj/1162-button-to-scroll-tools-to-the-right-or-left-doesnt-work-in-ie-or-old-edge
SO link that helped me:
https://stackoverflow.com/questions/51517324/scrollto-method-doesnt-work-in-edge
> Fixed scrollTo not working in IE11

- src/components/NotesPanel/VirtualizedList/VirtualizedList.js
When adding new annotations (mainly text ones like highlight, underline, etc)  the following happens (this affect 7.0 and 6.X)
The issue is when we have a lot of comments (more than the NotesPanel.js `VIRTUALIZATION_THRESHOLD` of 100), and start adding more, we use the `VirtualizedLIst.js` component that is buggy. The issue seem to be it's not recalculating the height of notes so the overlapping happens.
My fix is to recalculate height when new notes are added
> [Bugfix] Fix issue with overlapping comments

- src/components/ThumbnailControls/ThumbnailControls.js
- src/components/ThumbnailsPanel/ThumbnailsPanel.js
- Calling "this.onDocumentLoaded()" manually if document is already loaded.
https://trello.com/c/H15Wx2wX/1176-rotation-buttons-shouldnt-be-displayed-in-the-thumbnail-panel-when-loading-with-wvs
> Rotation buttons shouldn't be displayed in the thumbnail panel when loading with WVS

- src/components/ZoomOverlay/ZoomOverlay.js
- src/constants/zoomFactors.js
- src/helpers/zoom.js
Zoom in and out functionality is now more predictable and bit more gradual (more steps). See code comment below for the functionality.
https://trello.com/c/gje4MpLD/1014-weird-increments-decrements-in-zoom-level
```
/**
* zoomIn works as follows. Every time user zooms in we take current zoom level and compare it to
* zoom factors map which currently is :
* {
'0.075': [null, 0.8],
'0.25': [0.8, 1.5],
'0.5': [1.5, 2.5],
'1': [2.5, 4],
'2': [4, 8],
'4': [8, 32],
'8': [32, 64],
'16': [64, null],
}
* Based on the range we select step size from this map. For example if current zoom level is 110% (1.1)
* then we can see that it falls to range [0.8, 1.5] and step size for this is 0.25. We add this step
* to current level so we end up to 1.35. We also store this step to stack so we can follow how …
```
> [BUGFIX] Zoom in and zoom out steps are now more predictable

- src/components/Thumbnail/Thumbnail.scss
This was because the positioning on the page and annotation layers didn't quite match up
The annotation layer was absolutely positioned and the page wasn't.
This change just gives them the same CSS styles so they overlap exactly.
To verify load a PDF and add a rectangle over the middle of some text. Check the thumbnail and previously you would see the rectangle is slightly shifted down compared to where it should be. Now they should match much more closely. 
It can be easier to tell if you use the browser zoom to zoom in.
> Fix issue where the annotation layer that overlaps the thumbnail doesn't quite line up

- src/components/AnnotationPopup/AnnotationPopup.js
When editing a free text or callout annotation in IE11, the text cursor will appear but not allow you to enter text until you click on the location you want to edit or select text. The culprit is the `react-draggable` component around the `AnnotationPopup` component. The reason is unclear (IE11 doesn't like something it does?).
This PR corrects the issue by removing draggable when using IE since it works in 'real' browsers.
> [Bugfix] Fixed issue where user could not immediately edit free text in IE11

- src/components/Bookmark/EditingBookmark.scss
- src/components/BookmarksPanel/BookmarksPanel.scss
- src/components/CalibrationModal/CalibrationModal.scss
- src/components/LinkModal/LinkModal.scss
- src/components/PrintModal/PrintModal.scss
- src/components/PrintModal/WatermarkModal/WatermarkModal.scss
- src/constants/modal.scss
Fixed issue with buttons being cut off in IE11 since `fit-content` was not supported. This PR uses the solution proposed by @khein-pdftron which seems to work.
> [Bugfix] Fixed buttons being cut off in IE11

- src/components/MeasurementOverlay/MeasurementOverlay.js
The issue occurs when checks were performed using the `TouchEvent` type which doesn't exist in IE11. This PR swaps the check to check for the `touches` property first before the type.
> [Bugfix] Fixed touch errors coming up in IE11 when creating measurement annots

- src/components/NotesPanel/VirtualizedList/VirtualizedList.js
- src/components/PageNavOverlay/PageNavOverlay.js
We are using css variable for shifting the page nav which doesn't work in IE11
> [Bugfix] Fix page nav overlay for IE11

- src/components/PrintModal/PrintModal.js
Fixes:
https://trello.com/c/apaiD3Y8/1195-printing-with-legacy-ui-doesnt-check-the-include-annotations-box-by-default
> Select print annotations by default

- src/components/ThumbnailsPanel/ThumbnailsPanel.js
The issue occurs when you load a document with enough pages to get a scroll bar in the page thumbnails panel, open the page thumbnails panel, full-screen WebViewer, and then exit full-screen. The inner thumbnail panel will be slightly longer than expected and the bottom of the panel will be offscreen. The update of the size is handled by the `Measure` component, but it will not trigger `onResize` since the panel did not resize when exiting full-screen.
This PR makes the component listen to the window resize event and updates the size using the container size which will be correct when exiting full-screen.
> [6.3] [Bugfix] Fixed issue where thumbnail panel was the wrong size after full screen

- src/apis/print.js
- src/components/MenuOverlay/MenuOverlay.js
- src/components/PrintModal/PrintModal.js
- src/helpers/hotkeysManager.js
- src/helpers/print.js
PrintModal should have logic only for rendering the component, so made sense to move it out of PrintModal and into PrintHelper. 
Testing it on dev freezes Chrome due to react/chrome issue:
facebook/react: Issue #17155
facebook/react: Issue #16734
So to test it out, build the UI and place it in WebViewer 7.0.
Ran through all combinations and ensured nothing broke.
> Moved out logic from PrintModal to Print Helper

- src/components/LinkModal/LinkModal.js
- src/components/LinkModal/LinkModal.scss
The link modal creates a dropdown with an option for every page number
so for large documents (thousands of pages) this can take quite a while
to render.
This change updates the behavior so that you can type the page number
instead and the link button is disabled if the page is out of bounds.
> Refactor link modal to improve the performance of documents with many pages

- src/components/Button/Button.js
As title described. Can elaborate if more information is needed.
> fix(Button): the title prop is still used for aria-label when the ariaLabel prop is passed

- src/constants/map.js
When an annotation has no associated icon, opening the NotesPanel crashes the UI. This PR gives it a default.
> [Bugfix] Fixed UI crash due to undefined icon

- src/apis/index.js
- src/apis/setPrintedNoteDateFormat.js
- src/components/PrintModal/PrintModal.js
- src/helpers/print.js
- src/redux/actions/exposedActions.js
- src/redux/initialState.js
- src/redux/reducers/viewerReducer.js
- src/redux/selectors/exposedSelectors.js
Added a new API `setPrintedNoteDateFormat` to set the format of dates displayed on the notes page when printing.
> Added new API to set date format of printed notes

- src/components/MeasurementOverlay/LineMeasurementInput.js
Currently `annotationChanged` get fired
1. Before the "add" event when adding new line dimension
2. Selecting and deselecting line dimension will trigger the `annotationChanged` event
This is because we are always calling "setLineLength" which fires `annotationChanged`. Also when creating new annotation, the `foreLineRedraw` function is being called which trigger a "modify" `annotationChanged` before the "add" event get fired
> [Bugfix] Fix random "annotationChanged" event firing with measurement tool

- i18n/translation-nl.json
Hello!
We're using PDFTron in our application and some of our users are Dutch. Today we received a support ticket asking to update a translation that's not entirely correct, so I'm opening a Pull Request to update that.
From Google Translate:
"Geen een wachtwoord" translates to "Not a password".
"Geef een wachtwoord" translates to "Enter a password".
> Updated Dutch translation into a more appropriate one.
